version: "3.7"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
    condition: on-failure
  update_config:
    parallelism: 1
    delay: 10s

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.2-latest
    env_file: 
      - ./envs/zabbix-server/common.env
    volumes:
        - ./data_internal/zabbix-server/externalscripts:/usr/lib/zabbix/externalscripts:ro
        - ./data_internal/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts:ro
    networks:
      - "monitoring-network"
    ports:
      - "10051:10051"
    deploy: *template-deploy
  
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.2-latest
    env_file: 
      - ./envs/zabbix-frontend/common.env
    networks:
      - "monitoring-network"    
    ports:
      - "80:8080"
    deploy: *template-deploy

networks: 
  monitoring-network: